package compair

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestSuggestCompairIgnoreFindsGeneratedSurfaces(t *testing.T) {
	root := t.TempDir()
	runGit(t, root, "init")
	writeTestFile(t, root, "go.mod", "module example.com/demo\n\ngo 1.24\n")
	writeTestFile(t, root, "go.sum", "example.com/dep v1.0.0 h1:abc\n")
	for _, name := range []string{"a.pb.go", "b.pb.go", "c.pb.go"} {
		writeTestFile(t, root, filepath.Join("proto", name), "// Code generated by protoc. DO NOT EDIT.\npackage proto\n")
	}
	for _, name := range []string{"run.md", "sdk.md"} {
		writeTestFile(t, root, filepath.Join("internal", "studio", "sdk", "docs", "sdks", name), "<!-- This file was automatically generated. -->\n")
	}
	for _, name := range []string{"search.png", "flow.svg", "demo.mp4"} {
		writeTestFile(t, root, filepath.Join("content", "docs", "insights", "assets", name), "media")
	}
	runGit(t, root, "add", ".")

	report, err := suggestCompairIgnore(root, ignoreSuggestOptions{
		MinLargeFileBytes: 250000,
		MinDirFiles:       2,
		MinDirBytes:       1,
		IncludeReview:     true,
	})
	if err != nil {
		t.Fatal(err)
	}
	got := map[string]bool{}
	for _, s := range report.Suggestions {
		got[s.Pattern] = true
	}
	for _, want := range []string{"go.sum", "*.pb.go", "internal/studio/sdk/docs/", "content/docs/insights/assets/"} {
		if !got[want] {
			t.Fatalf("missing suggested pattern %q in %#v", want, report.Suggestions)
		}
	}
}

func TestSuggestCompairIgnoreFindsLargeLowSignalRepoSurfaces(t *testing.T) {
	root := t.TempDir()
	runGit(t, root, "init")
	writeTestFile(t, root, "package.json", "{}\n")
	writeTestFile(t, root, filepath.Join("packages", "browser", "src", "__tests__", "extensions", "test_data", "sessionrecording-utils-test-data.ts"), "export const replay = []\n")
	writeTestFile(t, root, filepath.Join("packages", "rrweb", "rrweb", "test", "replay", "__image_snapshots__", "shot.png"), "media")
	writeTestFile(t, root, filepath.Join("frontend", "src", "__mocks__", "large-response.json"), "{}\n")
	writeTestFile(t, root, filepath.Join("static", "wp-content", "uploads", "hero.gif"), "media")
	writeTestFile(t, root, filepath.Join("src", "components", "Home", "lotties", "hero.json"), "{}\n")
	writeTestFile(t, root, filepath.Join("frontend", "src", "api.schemas.ts"), "// Generated by schema tooling. Do not edit.\n"+strings.Repeat("export type Generated = string\n", 4096))
	runGit(t, root, "add", ".")

	report, err := suggestCompairIgnore(root, ignoreSuggestOptions{
		MinLargeFileBytes: 250000,
		MinDirFiles:       1,
		MinDirBytes:       1,
		IncludeReview:     true,
	})
	if err != nil {
		t.Fatal(err)
	}
	got := map[string]bool{}
	for _, s := range report.Suggestions {
		got[s.Pattern] = true
	}
	for _, want := range []string{
		"packages/browser/src/__tests__/extensions/test_data/",
		"packages/rrweb/rrweb/test/replay/__image_snapshots__/",
		"frontend/src/__mocks__/",
		"static/wp-content/",
		"src/components/Home/lotties/",
		"api.schemas.ts",
	} {
		if !got[want] {
			t.Fatalf("missing suggested pattern %q in %#v", want, report.Suggestions)
		}
	}
}

func TestWriteCompairIgnoreSuggestionsSkipsReviewByDefault(t *testing.T) {
	root := t.TempDir()
	suggestions := []ignoreSuggestion{
		{Pattern: "go.sum", Confidence: "high", Reason: "generated"},
		{Pattern: "large-fixture.json", Confidence: "review", Reason: "large"},
	}
	written, err := writeCompairIgnoreSuggestions(root, suggestions, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(written) != 1 || written[0] != "go.sum" {
		t.Fatalf("unexpected written patterns: %#v", written)
	}
	content, err := os.ReadFile(filepath.Join(root, ".compairignore"))
	if err != nil {
		t.Fatal(err)
	}
	if string(content) == "" || !strings.Contains(string(content), "go.sum") || strings.Contains(string(content), "large-fixture.json") {
		t.Fatalf("unexpected .compairignore content:\n%s", string(content))
	}
}

func runGit(t *testing.T, root string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", append([]string{"-C", root}, args...)...)
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git %v failed: %v\n%s", args, err, string(out))
	}
}

func writeTestFile(t *testing.T, root, rel, content string) {
	t.Helper()
	path := filepath.Join(root, rel)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
